### PR TITLE
Bugfix/authentication

### PR DESCRIPTION
**Pull request by odonnell-pb**
@MikaBerglund Please review and let me know if you need any changes. This is my first contribution to any github project so all feedback is gratefully received.

**Currently implemented:**

- Getting the Auth Token now uses the MSTeamsSDK getAuthToken per [Single sign-on (SSO) support for tabs](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/auth-aad-sso)
- AuthenticationProvider now exchanges the token from Teams for use with MS Graph using the On_Behalf-Flow
- ConfigureAwait(true) added to some of the method calls. This usually marshalls the result back to the calling thread and for me allowed debugging to work. There are some patterns that could be looked at to remove some of this ceremony code. I've only added the ConfigureAwait in the code paths I was working in.

**Impacts:**
- The AuthToken is passed around as a JwtSecurityToken and replaces AuthenticationResult
- Currently the popup for consent will only work for the (currently) supported scopes - email, profile, offline_access, OpenId. Adding User.Read, Mail.Read or other scopes does work, but the tenant admin must perform the consent. For me, this is OK, however, [Navigate to the authorization page from your popup page](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/auth-tab-aad#navigate-to-the-authorization-page-from-your-popup-page) will need to be investigated.
- 

**Other:**
- Moved the appsettings configuration registration into the BlazoradeTeams extension methods ensuring BlazoradeTeams is managing the configuration. This resulted in passing around IOptions<AzureAsApplicationOptions> which I don't think is a bad thing.

There are probably other changes as well - I use Resharper and will use the code cleanup suggestions pretty much unconsciously these days - I hope that's not a problem :)

### CODE REVIEW

**Comment by odonnell-pb** [comment]
Also, your appsettings.local json will need 2 further properties - 
    "clientSecret": "xxxxxxxx",
    "aadInstance": "https://login.microsoftonline.com/",

where the client secret is created in the AzureAD application - this is needed as part of the On-Behalf-Of flow when exchanging the token for use with MS Graph

**Comment by MikaBerglund** [comment]
Thanks! I'll look into this during the weekend. As I already wrote, I will probably not merge this completely as is, but rather pick parts of it. The main reason is that the solution that you linked to in your comment on issue #12 is very limited related to what permissions you can acquire a token for.

Another thing that needs to be addressed is the use of a client secret in the configuration. As Blazorade Teams also supports Blazor WebAssembly, we can't rely on authentication flows that require a client secret.

At some point later on, we might want to start supporting authentication also with Azure AD B2C, in which case we would need to be able to configure also the AAD instance. Until then, we need only the tenant ID, which can also be `common` for multi-tenant applications.

But still, thank you for the effort you've put in. I will look into it.

**Comment by MikaBerglund** [comment]
I had a quick scroll through the changes in your PR. One thing that I wanted to point out, which I guess applies to any kind of PR, both on GitHub and elsewhere.

When you make changes, try to stick to those things that actually are changes. It might be a good idea to turn off any automatic formatting or refactoring. It will still end up as a change in the history and take away the focus on the real deal. I would suspect that you are using some kind of refactoring tool that has for instance changed `async override` to `override async`. Another example is the removal of `this` prefix. I know that it is not necessary, but I use it to explicitly show intent, that I am referencing a module level member, and not a static member or a member within a method scope for instance.

Just some pointers for future PRs.

**Comment by odonnell-pb** [comment]
No worries. 
I am going to be adding more code over the next day or two to solve the consenting for additional scopes - it looks fairly straight forward to do.

SSO with web assembly will not work without a backend token exchange API for the very reason you pointed out - the client secret should not be exposed in the front-end. This means for SSO support in web assembly, it will not run as a static page.

Perhaps there needs to be some thought put into options for supporting different authentication strategies using SSO, B2C, non AAD auth providers and static web assembly delivery? I don't think there's a one size strategy that will suit everyone. I'd be interested in hearing your thoughts on this.

I will commit against this PR for now.

**Comment by MikaBerglund** [comment]
What I am trying to do is to find a solution that works both for Blazor Server and Blazor WebAssembly. At the end of the day, any solution that works with WebAssembly should work with server as well.

In the version that currently is published as a Nuget package, the authentication already works with MSAL and using popup login in MSAL as fallback. The problem with that approach is that it does not work in Teams Desktop client, because of the popup implemnetation in MSAL. That's why I am going to change it to using the popup dialog provided by the Teams SDK, and using login redirect from MSAL in that dialog.

**Comment by odonnell-pb** [comment]
Having read this again (https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/auth-aad-sso#known-limitations) using the Teams SSO approach, I think that you will struggle to get additional scopes from AAD without having a server-side API to exchange the token go get the additional permissions, the documentation suggests that's what is required. Still, I don't know enough about MSAL to comment.

In any case, I have implemented a rudimentary SSB solution for requesting additional permissions for MS Graph (as the default) or any other API . It's now opt-in and can be added in Startup using AddBlazoradeTeamSSO. I've implemented it in such a way that when you need additional permissions it can be requested (and consented if needed). This will ensure the downstream API is being sent only those permissions it is entitled to.

I need to add a demo - perhaps by having another personal tab. I am thinking I will revert the UserInfoView to your original code as that still worked in the Teams Web Client.

Take a look at this and if it doesn't suit your design goals, that's fine. It solves mine and may be useful for others as well.

**Comment by MikaBerglund** [comment]
You may be right, if trying to implement an SSO solution using the [article you linked to](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/auth-aad-sso). However, that approach is not the one I'm working on. I am a bit more towards the [AD authentication option](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/auth-tab-aad) that includes using the authentication dialog provided by Teams using the `microsoftTeams.authentication.authenticate()` function.

For the actual token acquisition and authentication, I use MSAL instead of just redirecting to the authorization endpoint in Azure AD from my code. This will effectively create an SSO solution where the user may have to grant consent and log in the very first time they use the application. After that, MSAL will take care of caching access tokens and refresh tokens even across sessions.

Since I am using the browser version of MSAL, which works completely on the client as a public application, the application is not authenticated with a client secret, but with the help of the redirect URL configured on the Azure AD application registration.

This will then also enable an application to acquire access tokens to any API that has been configured on the Azure AD application registration, not just the limited scopes to Microsoft Graph that the SSO solution provided by Teams supports.

**Comment by MikaBerglund** [comment]
The problem described in #12 is now resolved with the PR #14, so I'll close this PR as it is a duplicate.

**Pull request closed without merging**
